// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABBAe8k5S2pITAEX9C4q_JcNGhBRteDck',
    appId: '1:849453640242:web:3d410ad5a85c922bb5aa2b',
    messagingSenderId: '849453640242',
    projectId: 'booking-app-14205',
    authDomain: 'booking-app-14205.firebaseapp.com',
    storageBucket: 'booking-app-14205.firebasestorage.app',
    measurementId: 'G-1TE1HBY8C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2eBOMdhm3sVI_QgMqOPFI_Hf112_ns-g',
    appId: '1:849453640242:android:d4ea7fc705d03df7b5aa2b',
    messagingSenderId: '849453640242',
    projectId: 'booking-app-14205',
    storageBucket: 'booking-app-14205.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLcdwP573v91CpuJZtDbx-nv5KA87jvJ0',
    appId: '1:849453640242:ios:c70d53536bedeb7ab5aa2b',
    messagingSenderId: '849453640242',
    projectId: 'booking-app-14205',
    storageBucket: 'booking-app-14205.firebasestorage.app',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLcdwP573v91CpuJZtDbx-nv5KA87jvJ0',
    appId: '1:849453640242:ios:c70d53536bedeb7ab5aa2b',
    messagingSenderId: '849453640242',
    projectId: 'booking-app-14205',
    storageBucket: 'booking-app-14205.firebasestorage.app',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABBAe8k5S2pITAEX9C4q_JcNGhBRteDck',
    appId: '1:849453640242:web:71b1f2168ceee043b5aa2b',
    messagingSenderId: '849453640242',
    projectId: 'booking-app-14205',
    authDomain: 'booking-app-14205.firebaseapp.com',
    storageBucket: 'booking-app-14205.firebasestorage.app',
    measurementId: 'G-4EKWT11RFR',
  );
}
